### ISSUE TITLE
Swap numbers using bitwise operators error

### ISSUE THREAD

**Issue by xiankaing** [uclaupe-tutoring/practice-problems#1]
Contributed by Michael Germano.

Write a function to swap two input integers (passed by reference) in place. This swap should be done with no additional space (no temporary integers) and using only bitwise operators.

Solution

void swap(int &a, int &b) {
    if (a == b)
      return;  //this doesn't need to be here

    a ^= b;
    b ^= a;
    a ^= b;
}
To see how this works let's look at an example using a = 15, and b = 6.

a in binary is 1111. b in binary is 0110.

First we set a = 1111 ^ 0110 = 1001. Next we set b = 0110 ^ 1001 = 1111. Finally we set a = 1001 ^ 1111 = 0110.

Note: The if-check is needed for the instance when both numbers are the same, since a ^ a = 0 and thus our method will not work. 
**//^WRONG**
//a^=a => a=0
//b^=a => b=b
//a^=b => a=b
//this doesn't matter  because a and b are the same value.

**Comment by Daniel-Norman** [comment]
Checked and edited. Thank you for letting us know!

**Comment by xiankaing** [comment]
dope

On Jun 8, 2017 3:08 PM, "Daniel Norman" <notifications@github.com> wrote:

Closed #1 <https://github.com/uclaupe-tutoring/practice-problems/issues/1>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/uclaupe-tutoring/practice-problems/issues/1#event-1116349776>,
or mute the thread

**Comment by xiankaing** [comment]
oh the concern was not if the values are the same but if the address are the same 
So the if check should strictly be if(&a==&b)
